### ISSUE TITLE
There is no url methode in the HtmlHelper

### ISSUE THREAD

**Issue by matthiasmoritz** [fheider/cakephp-datatables#1]
In 'Usage', you write something like 
$this->Html->url(['action' => 'index'])

But there is no url methode in the HtmlHelper.
http://api.cakephp.org/3.0/class-Cake.View.Helper.HtmlHelper.html

**Comment by gildonei** [comment]
You can use a string to specify your controller/action to request data like "/users/index"

**Comment by fheider** [comment]
I fixed it. Use Router::url instead.

In my projects I extend the HtmlHelper with an url function to shorten the Router::url (you only need one use) action.
