### ISSUE TITLE
Actions column

### ISSUE THREAD

**Issue by gildonei** [fheider/cakephp-datatables#2]
How can I specify or add a column with an actions button to allow user to edit, delete.

![datatables](https://cloud.githubusercontent.com/assets/1370979/9959188/224c7ad0-5de8-11e5-9150-84a1e027f322.png)

**Comment by fheider** [comment]
I solved it like this:

First add an actions column:

```
[
    'orderable' => false,
    'data' => null,
    'defaultContent' => '<a href="#" class="btn-details">Details</a>'
]
```

Then add your action:

```
$('.table').on('click', 'tbody .btn-details', function(e) {
    e.preventDefault();
    currentRow = $(this).parents('tr');
    window.location.href = '<?= Router::url(['action' => 'details']) ?>/' + table.api().row(currentRow).data().id;
});
```
