### ISSUE TITLE
Use callback functions on DataTables->init

### ISSUE THREAD

**Issue by gildonei** [fheider/cakephp-datatables#3]
how could I use callback function like "rowCallback" - https://datatables.net/examples/server_side/select_rows.html -  on $this->DataTables->init([...

**Comment by ypnos-web** [comment]
DataTablesHelper uses json to communicate options with datatables so it is not possible to pass javascript functions through `init()`.

My pull request #13 is very related to this. If you apply #13, you can write your custom js function somewhere else and let it be called after initialization. In your js you can add the callback. I haven't tried that yet though.

**Comment by ypnos-web** [comment]
Have a look at #14

**Comment by gildonei** [comment]
Thanks!
